<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pages extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Page');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'pages/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'pages/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'pages/index.html';
            $config['first_url'] = base_url() . 'pages/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Page->total_rows($q);
        $pages = $this->Page->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'pages_data' => $pages,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('pages/pages_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Page->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
	    );
            $this->load->view('pages/pages_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pages'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('pages/create_action'),
	    'id' => set_value('id'),
	);
        $this->load->view('pages/pages_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
	    );

            $this->Page->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('pages'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Page->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('pages/update_action'),
		'id' => set_value('id', $row->id),
	    );
            $this->load->view('pages/pages_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pages'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
	    );

            $this->Page->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('pages'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Page->get_by_id($id);

        if ($row) {
            $this->Page->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('pages'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pages'));
        }
    }

    public function _rules() 
    {

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Pages.php */
/* Location: ./application/controllers/Pages.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-04-05 15:14:13 */
/* http://harviacode.com */